from __future__ import annotations


DASHBOARD_HTML = """<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Markdown Knowledge Hub</title>
<style>
:root{color-scheme:light;--ink:#172033;--muted:#737c92;--line:#e5e9f2;--paper:#fff;--canvas:#f5f6fa;
--primary:#6558e8;--primary-soft:#efedff;--mint:#168761;--mint-soft:#e8f8f2;--amber:#ad7016;
--amber-soft:#fff4de;--rose:#b94057;--rose-soft:#fff0f3;--shadow:0 12px 35px #28324b0d}
*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--ink);background:var(--canvas);
font:14px/1.55 Inter,Pretendard,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}button,input,select{font:inherit}
button{cursor:pointer}.shell{width:min(1180px,calc(100% - 36px));margin:auto;padding:28px 0 56px}.topbar{display:flex;
align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.brand{display:flex;align-items:center;gap:13px}.brand-mark{
display:grid;place-items:center;width:44px;height:44px;border-radius:14px;color:white;font-size:18px;font-weight:850;
background:linear-gradient(145deg,#887df5,#5747d4);box-shadow:0 10px 24px #6558e83d}.brand h1{margin:0;font-size:19px;
letter-spacing:-.03em}.brand p{margin:1px 0 0;color:var(--muted);font-size:12px}.top-actions{display:flex;align-items:center;gap:9px}
.live{display:flex;align-items:center;gap:7px;padding:8px 12px;border:1px solid #d8eee5;border-radius:99px;background:#f3fbf8;
color:#147b59;font-size:12px;font-weight:750}.live-dot{width:7px;height:7px;border-radius:50%;background:#20be87;box-shadow:0 0 0 5px #20be8717}
.refresh,.secondary,.primary{display:inline-flex;align-items:center;justify-content:center;gap:7px;border-radius:11px;padding:9px 14px;
font-weight:700}.refresh,.secondary{border:1px solid var(--line);color:#535d74;background:white}.primary{border:1px solid var(--primary);
color:white;background:var(--primary)}.refresh:hover,.secondary:hover{color:var(--primary);border-color:#cfc9ff}.refresh:disabled,.primary:disabled{opacity:.55;cursor:wait}
.hero{position:relative;overflow:hidden;min-height:205px;padding:31px;border-radius:25px;color:white;background:linear-gradient(125deg,#4b47c5,#7065e9 55%,#9279f0);
box-shadow:0 22px 44px #5546d72b}.hero:before,.hero:after{content:"";position:absolute;border-radius:50%;background:white;opacity:.08}
.hero:before{width:290px;height:290px;right:-80px;top:-165px}.hero:after{width:175px;height:175px;right:170px;bottom:-135px}
.hero-inner{position:relative;z-index:1;display:flex;justify-content:space-between;align-items:flex-end;gap:25px}.eyebrow{margin-bottom:12px;color:#e6e3ff;font-size:12px;font-weight:750}
.hero h2{margin:0;font-size:clamp(27px,4vw,41px);line-height:1.16;letter-spacing:-.05em}.hero p{margin:12px 0 0;color:#e9e6ff;font-size:15px}
.hero-total{min-width:185px;padding:18px 21px;border:1px solid #ffffff35;border-radius:18px;background:#ffffff17;backdrop-filter:blur(8px)}
.hero-total span{display:block;color:#eceaff;font-size:12px}.hero-total strong{display:block;margin:2px 0;font-size:31px;letter-spacing:-.04em}
.alert{display:none;margin-top:15px;padding:13px 16px;border:1px solid #ffd0d8;border-radius:13px;color:var(--rose);background:var(--rose-soft)}
.nav{display:flex;gap:6px;margin:19px 0;padding:6px;border:1px solid var(--line);border-radius:15px;background:white;box-shadow:0 5px 18px #28324b09;overflow:auto}
.tab{display:flex;align-items:center;justify-content:center;gap:7px;min-width:124px;padding:10px 14px;border:0;border-radius:10px;color:#7c8497;background:transparent;font-weight:720;white-space:nowrap}
.tab:hover{color:var(--primary);background:#f8f7ff}.tab.active{color:#5144d2;background:var(--primary-soft)}.icon{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8}
.view{display:none}.view.active{display:block}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.stat{padding:20px;border:1px solid var(--line);border-radius:18px;background:white;box-shadow:var(--shadow)}
.stat-top{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:12px;font-weight:700}.stat-icon{display:grid;place-items:center;width:33px;height:33px;border-radius:10px;color:var(--primary);background:var(--primary-soft)}
.stat strong{display:block;margin-top:12px;font-size:27px;line-height:1;letter-spacing:-.04em}.stat small{display:block;margin-top:8px;color:#9ca4b5}.section-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:4px 0 15px}
.section-head h3{margin:0;font-size:20px;letter-spacing:-.03em}.section-head p{margin:2px 0 0;color:var(--muted)}.toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.field{border:1px solid var(--line);border-radius:10px;padding:9px 11px;color:#4c566e;background:white;outline:0}.field:focus{border-color:#aaa2f6;box-shadow:0 0 0 3px #6558e812}
.search-box{display:grid;grid-template-columns:1fr 210px auto;gap:10px;padding:17px;border:1px solid var(--line);border-radius:17px;background:white;box-shadow:var(--shadow);margin-bottom:14px}.search-box .field{padding:12px 13px}.workspace-grid,.pattern-grid,.prompt-grid,.tool-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.workspace,.pattern,.prompt-card,.result-card,.tool-card{padding:21px;border:1px solid var(--line);border-radius:19px;background:white;box-shadow:var(--shadow)}
.workspace-top,.pattern-top,.prompt-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.workspace-title{display:flex;align-items:center;gap:11px}.folder{display:grid;place-items:center;width:40px;height:40px;border-radius:12px;color:#6658df;background:#f0eeff}.folder .icon{width:21px;height:21px}.workspace h4,.pattern h4,.prompt-card h4,.result-card h4{margin:0;font-size:16px}.desc{margin-top:3px;color:var(--muted);font-size:12px}.status{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:99px;font-size:11px;font-weight:800}.status.ok{color:var(--mint);background:var(--mint-soft)}.status.warn{color:var(--amber);background:var(--amber-soft)}.status.bad{color:var(--rose);background:var(--rose-soft)}
.workspace-path{margin:16px 0;padding:9px 11px;border-radius:10px;color:#5d6680;background:#f7f8fb;font-size:12px;overflow-wrap:anywhere}.workspace-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.workspace-meta span{display:block;color:#9da5b6;font-size:10px;text-transform:uppercase}.workspace-meta strong{display:block;margin-top:2px;font-size:13px}
.activity-list,.result-list{display:grid;gap:10px}.activity{display:grid;grid-template-columns:40px minmax(150px,1.1fr) minmax(260px,2.2fr) auto;align-items:center;gap:14px;padding:16px 18px;border:1px solid var(--line);border-radius:16px;background:white}.activity-symbol{display:grid;place-items:center;width:37px;height:37px;border-radius:11px;color:#5e51dd;background:#f0eeff;font-weight:850}.activity h4{margin:0;font-size:14px}.activity time{color:#9ba3b5;font-size:11px}.activity-main{min-width:0}.query{margin-bottom:6px;color:#30394f;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chips{display:flex;flex-wrap:wrap;gap:5px}.chip{max-width:270px;padding:4px 8px;border-radius:7px;color:#687189;background:#f2f4f8;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.latency{text-align:right;color:#81899c;font-size:11px;white-space:nowrap}
.pattern .uses{color:#5144d2;font-size:22px;font-weight:850;text-align:right}.pattern .uses small{display:block;color:#9ba3b5;font-size:10px;font-weight:600}.pattern .chips{margin-top:14px}.pattern-foot{display:flex;justify-content:space-between;margin-top:16px;padding-top:12px;border-top:1px solid #eff1f5;color:#929aac;font-size:11px}
.result-card{box-shadow:none}.result-top{display:flex;justify-content:space-between;gap:12px}.result-card .excerpt{margin:13px 0;color:#626b80;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.result-path{color:#6558d8;font-size:11px;overflow-wrap:anywhere}.flow{display:flex;align-items:center;gap:7px;margin-bottom:15px;padding:14px 16px;border:1px solid #dedaff;border-radius:15px;color:#594dd1;background:#f8f7ff;overflow:auto;white-space:nowrap}.flow b{padding:6px 10px;border-radius:8px;background:white}.tool-card{box-shadow:none}.tool-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.tool-step{display:grid;place-items:center;min-width:31px;height:31px;border-radius:10px;color:#5b4ed5;background:var(--primary-soft);font-weight:850}.tool-card h4{margin:0;font-size:16px}.tool-name{margin-top:2px;color:#7569df;font:11px ui-monospace,Consolas,monospace}.tool-purpose{margin:14px 0;color:#596279}.tool-when{padding:10px 11px;border-radius:10px;color:#6e778d;background:#f7f8fb;font-size:12px}.tool-card .chips{margin-top:13px}.prompt-card{display:flex;flex-direction:column;min-height:230px}.prompt-tag{padding:4px 8px;border-radius:7px;color:#5649d3;background:var(--primary-soft);font-size:10px;font-weight:800;text-transform:uppercase}.prompt-preview{margin:14px 0;max-height:100px;overflow:hidden;color:#687188;white-space:pre-wrap;font-size:12px;mask-image:linear-gradient(#000 65%,transparent)}.prompt-actions{display:flex;gap:8px;margin-top:auto}.prompt-actions button{flex:1}.prompt-full{display:none;margin-top:12px;padding:13px;border-radius:11px;color:#4e586f;background:#f7f8fb;white-space:pre-wrap;max-height:340px;overflow:auto;font:12px/1.6 ui-monospace,Consolas,monospace}.prompt-card.open .prompt-full{display:block}.prompt-card.open .prompt-preview{display:none}
.pager{display:flex;align-items:center;justify-content:center;gap:7px;margin-top:17px}.pager button{min-width:36px;height:36px;border:1px solid var(--line);border-radius:9px;color:#687189;background:white}.pager button.active{color:white;border-color:var(--primary);background:var(--primary)}.pager button:disabled{opacity:.4;cursor:default}.empty{padding:45px 20px;border:1px dashed #d7dce8;border-radius:17px;color:#8e96a9;text-align:center;background:#fafbfe}.copy-toast{position:fixed;right:22px;bottom:22px;z-index:10;padding:11px 15px;border-radius:11px;color:white;background:#263149;box-shadow:0 12px 30px #17203338;opacity:0;transform:translateY(8px);pointer-events:none;transition:.2s}.copy-toast.show{opacity:1;transform:none}footer{display:flex;justify-content:space-between;gap:16px;margin-top:24px;color:#9ba3b4;font-size:11px}code{color:#6558d8}
@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}.workspace-grid,.pattern-grid,.prompt-grid,.tool-grid{grid-template-columns:1fr}.activity{grid-template-columns:40px 1fr auto}.activity-main{grid-column:2/4}.hero-inner{align-items:flex-start;flex-direction:column}.search-box{grid-template-columns:1fr 180px}.search-box .primary{grid-column:1/3}}
@media(max-width:560px){.shell{width:calc(100% - 24px);padding-top:17px}.brand p,.live{display:none}.hero{padding:24px}.hero h2{font-size:27px}.hero-total{width:100%}.stats{grid-template-columns:1fr}.tab{min-width:116px}.search-box{grid-template-columns:1fr}.search-box .primary{grid-column:auto}.activity{grid-template-columns:37px 1fr}.activity-main,.latency{grid-column:2}.latency{text-align:left}.workspace-meta{grid-template-columns:1fr 1fr}.section-head{align-items:flex-start;flex-direction:column}footer{flex-direction:column}}
</style></head><body><main class="shell">
<header class="topbar"><div class="brand"><div class="brand-mark">M</div><div><h1>Markdown Knowledge Hub</h1><p>Agent Docs 기반 로컬 지식 연결</p></div></div><div class="top-actions"><div class="live"><i class="live-dot"></i><span id="status-text">확인 중</span></div><button id="refresh" class="refresh" type="button">↻ 새로고침</button></div></header>
<section class="hero"><div class="hero-inner"><div><div id="mode-label" class="eyebrow">LOCAL KNOWLEDGE</div><h2>흩어진 Markdown 지식을<br>하나의 검색 경험으로</h2><p id="hero-copy">연결된 지식 공간과 사용 흐름을 한눈에 확인하세요.</p></div><div class="hero-total"><span>검색 가능한 문서</span><strong id="hero-docs">—</strong><span id="hero-roots">워크스페이스 확인 중</span></div></div></section><div id="error-box" class="alert"></div>
<nav class="nav" aria-label="대시보드 메뉴"><button class="tab active" data-tab="overview">⌂ 한눈에 보기</button><button class="tab" data-tab="search">⌕ 지식 검색</button><button class="tab" data-tab="workspaces">▱ 워크스페이스</button><button class="tab" data-tab="tools">◇ 도구 안내</button><button class="tab" data-tab="activity">↗ 사용 이력</button><button class="tab" data-tab="patterns">▥ 질문 패턴</button><button class="tab" data-tab="prompts">✦ 프롬프트</button></nav>
<section id="tab-overview" class="view active"><div class="stats"><article class="stat"><div class="stat-top"><span>연결된 공간</span><i class="stat-icon">▱</i></div><strong id="root-count">—</strong><small>검색 가능한 워크스페이스</small></article><article class="stat"><div class="stat-top"><span>캐시 준비</span><i class="stat-icon">◫</i></div><strong id="cache-count">—</strong><small>바로 검색 가능한 문서</small></article><article class="stat"><div class="stat-top"><span>누적 도구 호출</span><i class="stat-icon">↗</i></div><strong id="call-count">—</strong><small id="last-call">최근 호출 확인 중</small></article><article class="stat"><div class="stat-top"><span>평균 응답 시간</span><i class="stat-icon">◷</i></div><strong id="call-latency">—</strong><small id="call-errors">오류 확인 중</small></article></div></section>
<section id="tab-search" class="view"><div class="section-head"><div><h3>지식 검색</h3><p>연결된 모든 공간 또는 원하는 워크스페이스에서 바로 찾아보세요.</p></div></div><form id="knowledge-form" class="search-box"><input id="knowledge-query" class="field" placeholder="예: 지원 우선순위, 배포 체크리스트, MCP 설정" required><select id="knowledge-root" class="field"><option value="">모든 워크스페이스</option></select><button class="primary" type="submit">검색하기</button></form><div id="search-results" class="result-list"><div class="empty">검색어를 입력하면 관련 문서를 찾아드려요.</div></div><div id="search-pager" class="pager"></div></section>
<section id="tab-workspaces" class="view"><div class="section-head"><div><h3>연결된 워크스페이스</h3><p>각 공간의 문서와 인덱스 준비 상태입니다.</p></div><span id="updated"></span></div><div id="workspaces" class="workspace-grid"></div></section>
<section id="tab-tools" class="view"><div class="section-head"><div><h3>MCP 도구 안내</h3><p>질문을 찾고 근거를 읽는 데 사용하는 8개 도구입니다.</p></div></div><div class="flow"><b>1. 목록 확인</b><span>→</span><b>2. 공간 선택</b><span>→</span><b>3. 검색</b><span>→</span><b>4. 원문 읽기</b><span>→</span><b>5. 링크 확인</b></div><div id="tools" class="tool-grid"></div></section>
<section id="tab-activity" class="view"><div class="section-head"><div><h3>최근 사용 이력</h3><p>어떤 도구에 어떤 조건을 사용했는지 확인할 수 있어요.</p></div><div class="toolbar"><input id="activity-query" class="field" placeholder="검색어·경로 찾기"><select id="tool-filter" class="field"><option value="">모든 도구</option></select></div></div><div id="activity" class="activity-list"></div><div id="activity-pager" class="pager"></div></section>
<section id="tab-patterns" class="view"><div class="section-head"><div><h3>자주 사용한 질문 패턴</h3><p>반복해서 사용한 도구와 조건을 모았습니다. 문서 본문은 저장하지 않아요.</p></div><input id="pattern-query" class="field" placeholder="패턴 검색"></div><div id="patterns" class="pattern-grid"></div><div id="pattern-pager" class="pager"></div></section>
<section id="tab-prompts" class="view"><div class="section-head"><div><h3>바로 쓰는 프롬프트</h3><p>Codex, Claude Code, Gemini CLI 설치와 검색 프롬프트를 복사하세요.</p></div><div class="toolbar"><input id="prompt-query" class="field" placeholder="프롬프트 검색"><select id="prompt-category" class="field"><option value="">전체</option></select></div></div><div id="prompts" class="prompt-grid"></div></section>
<footer><span>MCP <code>/mcp</code> · 상태 <code>/healthz</code> · 사용 이력 <code>/api/activity</code></span><span>10초마다 자동 업데이트</span></footer></main><div id="copy-toast" class="copy-toast">프롬프트를 복사했습니다</div>
<script>
const $=id=>document.getElementById(id),state={activityPage:1,patternPage:1,searchPage:1,prompts:[],tools:[],roots:[]};
const num=v=>new Intl.NumberFormat('ko-KR').format(Number(v||0)),safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const when=v=>v?new Date(v).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'기록 없음';
const names={search_markdown:'워크스페이스 검색',search_all_markdown:'전체 동시 검색',find_relevant_markdown_roots:'관련 공간 찾기',read_markdown:'문서 읽기',get_markdown_links:'연결 문서 확인',list_markdown_roots:'워크스페이스 목록',get_source_graph_status:'인덱스 상태 확인',refresh_markdown_root:'검색 캐시 갱신',dashboard_search:'대시보드 검색'};
const rootsOf=d=>Array.isArray(d.roots)?d.roots:(d.root?[d.root]:[]);function rootState(r){if(!r.mounted||!r.mps_index_present||!r.supported||r.source_error)return['bad','확인 필요'];if(r.stale)return['warn','업데이트 필요'];return['ok','준비 완료']}
function chips(p){let keys=['query','root_id','root_ids','relative_path','limit','limit_per_root','sort_by','direction','start_line','max_lines','page'];return keys.filter(k=>p[k]!=null).map(k=>`<span class="chip">${safe(k==='query'?'검색어':k)} · ${safe(Array.isArray(p[k])?p[k].join(', '):p[k])}</span>`).join('')||'<span class="chip">기본 설정</span>'}
function resultText(c){if(c.error)return c.error;let r=c.result||{};if(r.result_count!=null)return`${num(r.result_count)}개 결과`;if(r.item_count!=null)return`${num(r.item_count)}개 항목`;if(r.total_lines!=null)return`${num(r.total_lines)}줄 문서`;if(r.candidate_count!=null)return`${num(r.candidate_count)}개 후보`;return'완료'}
function pager(id,p,kind){let el=$(id);if(!p||p.pages<=1){el.innerHTML='';return}let start=Math.max(1,p.page-2),end=Math.min(p.pages,start+4);start=Math.max(1,end-4);let html=`<button data-kind="${kind}" data-page="${p.page-1}" ${p.page<=1?'disabled':''}>‹</button>`;for(let i=start;i<=end;i++)html+=`<button data-kind="${kind}" data-page="${i}" class="${i===p.page?'active':''}">${i}</button>`;html+=`<button data-kind="${kind}" data-page="${p.page+1}" ${p.page>=p.pages?'disabled':''}>›</button>`;el.innerHTML=html}
function renderHealth(d){let roots=rootsOf(d),valid=roots.filter(r=>r.supported&&r.mps_index_present),docs=roots.reduce((s,r)=>s+Number(r.source_documents||0),0),cached=roots.reduce((s,r)=>s+Number(r.cached_documents||0),0);state.roots=roots;$('status-text').textContent=d.status==='ok'?'정상 연결':d.status==='degraded'?'일부 확인 필요':'연결 확인 필요';$('mode-label').textContent=(d.mode||'local').toUpperCase()+' MODE';$('hero-docs').textContent=num(docs);$('hero-roots').textContent=`${valid.length}개 워크스페이스 연결`;$('root-count').textContent=num(valid.length);$('cache-count').textContent=num(cached);$('hero-copy').textContent=d.status==='ok'?'모든 지식 공간이 준비되었습니다. 필요한 내용을 바로 찾아보세요.':'일부 연결 상태를 확인해 주세요.';let error=[d.error,d.action].filter(Boolean).join(' · ');$('error-box').style.display=error?'block':'none';$('error-box').textContent=error;$('updated').textContent='마지막 확인 '+new Date().toLocaleTimeString('ko-KR');$('workspaces').innerHTML=roots.length?roots.map(r=>{let st=rootState(r);return`<article class="workspace"><div class="workspace-top"><div class="workspace-title"><i class="folder">▱</i><div><h4>${safe(r.root_id)}</h4><div class="desc">${safe(r.description||'Markdown 지식 공간')}</div></div></div><span class="status ${st[0]}">${st[1]}</span></div><div class="workspace-path">${safe(r.public_path)}</div><div class="workspace-meta"><div><span>문서</span><strong>${num(r.source_documents)}개</strong></div><div><span>캐시</span><strong>${r.cached?num(r.cached_documents)+'개':'준비 전'}</strong></div><div><span>최근 인덱스</span><strong>${safe(when(r.source_updated_at))}</strong></div></div></article>`}).join(''):'<div class="empty">연결된 워크스페이스가 없습니다.</div>';let current=$('knowledge-root').value;$('knowledge-root').innerHTML='<option value="">모든 워크스페이스</option>'+valid.map(r=>`<option value="${safe(r.root_id)}">${safe(r.root_id)}</option>`).join('');$('knowledge-root').value=valid.some(r=>r.root_id===current)?current:''}
function renderActivity(d){let s=d.summary||{},calls=d.calls||[];$('call-count').textContent=num(s.total_calls);$('call-latency').textContent=s.average_duration_ms==null?'—':num(s.average_duration_ms)+' ms';$('call-errors').textContent=`실패 ${num(s.error_calls)}건`;$('last-call').textContent=s.last_called_at?'최근 '+when(s.last_called_at):'아직 호출 없음';$('activity').innerHTML=calls.length?calls.map(c=>`<article class="activity"><div class="activity-symbol">${c.status==='success'?'✓':'!'}</div><div><h4>${safe(names[c.tool]||c.tool)}</h4><time>${safe(when(c.called_at))}</time></div><div class="activity-main"><div class="query">${safe(c.params.query||c.params.relative_path||resultText(c))}</div><div class="chips">${chips(c.params)}</div></div><div class="latency"><span class="status ${c.status==='success'?'ok':'bad'}">${c.status==='success'?'성공':'실패'}</span><br>${num(c.duration_ms)} ms · ${safe(resultText(c))}</div></article>`).join(''):'<div class="empty">조건에 맞는 MCP 사용 이력이 없습니다.</div>';let selected=$('tool-filter').value,tools=d.tools||[];$('tool-filter').innerHTML='<option value="">모든 도구</option>'+tools.map(t=>`<option value="${safe(t)}">${safe(names[t]||t)}</option>`).join('');$('tool-filter').value=tools.includes(selected)?selected:'';pager('activity-pager',d.pagination,'activity')}
function renderPatterns(d){let items=d.patterns||[];$('patterns').innerHTML=items.length?items.map(p=>`<article class="pattern"><div class="pattern-top"><div><h4>${safe(names[p.tool]||p.tool)}</h4><div class="desc">${safe(p.params.query||p.params.relative_path||'기본 호출')}</div></div><div class="uses">${num(p.uses)}<small>사용 횟수</small></div></div><div class="chips">${chips(p.params)}</div><div class="pattern-foot"><span>평균 ${num(p.average_duration_ms)} ms</span><span>최근 ${safe(when(p.last_used_at))}</span></div></article>`).join(''):'<div class="empty">조건에 맞는 질문 패턴이 없습니다.</div>';pager('pattern-pager',d.pagination,'pattern')}
function renderSearch(d){let items=d.results||[];$('search-results').innerHTML=items.length?items.map(r=>`<article class="result-card"><div class="result-top"><div><h4>${safe(r.title||r.relative_path)}</h4><div class="desc">${safe(r.root_id)} · ${safe(when(r.modified_at))}</div></div><span class="status ok">읽기 가능</span></div><div class="excerpt">${safe(r.excerpt||'미리보기가 없습니다.')}</div><div class="result-path">${safe(r.path||r.relative_path)}</div></article>`).join(''):'<div class="empty">검색 결과가 없습니다. 다른 표현으로 찾아보세요.</div>';pager('search-pager',d.pagination,'search')}
function renderPrompts(){let q=$('prompt-query').value.toLowerCase(),cat=$('prompt-category').value,items=state.prompts.filter(p=>(!cat||p.category===cat)&&(!q||(p.title+' '+p.content).toLowerCase().includes(q)));$('prompts').innerHTML=items.length?items.map((p,i)=>`<article class="prompt-card" data-prompt="${safe(p.id)}"><div class="prompt-top"><div><h4>${safe(p.title)}</h4><div class="desc">${safe(p.id)}</div></div><span class="prompt-tag">${safe(p.category)}</span></div><div class="prompt-preview">${safe(p.content)}</div><div class="prompt-full">${safe(p.content)}</div><div class="prompt-actions"><button class="secondary prompt-toggle" type="button">전체 보기</button><button class="primary prompt-copy" type="button">복사하기</button></div></article>`).join(''):'<div class="empty">조건에 맞는 프롬프트가 없습니다.</div>'}
function renderTools(){ $('tools').innerHTML=state.tools.map(t=>`<article class="tool-card"><div class="tool-top"><div><h4>${safe(t.label)}</h4><div class="tool-name">${safe(t.name)}</div></div><span class="tool-step">${safe(t.step)}</span></div><div class="tool-purpose">${safe(t.purpose)}</div><div class="tool-when"><b>언제?</b> ${safe(t.when)}</div><div class="chips">${(t.parameters||[]).map(p=>`<span class="chip">${safe(p)}</span>`).join('')||'<span class="chip">파라미터 없음</span>'}</div><div class="desc" style="margin-top:12px"><b>반환:</b> ${safe(t.returns)}</div></article>`).join('') }
async function fetchActivity(){let u=`./api/activity?page=${state.activityPage}&page_size=10&tool=${encodeURIComponent($('tool-filter').value)}&q=${encodeURIComponent($('activity-query').value)}`;renderActivity(await(await fetch(u,{cache:'no-store'})).json())}async function fetchPatterns(){let u=`./api/patterns?page=${state.patternPage}&page_size=8&q=${encodeURIComponent($('pattern-query').value)}`;renderPatterns(await(await fetch(u,{cache:'no-store'})).json())}
async function runSearch(){let q=$('knowledge-query').value.trim();if(!q)return;let u=`./api/search?q=${encodeURIComponent(q)}&root_id=${encodeURIComponent($('knowledge-root').value)}&page=${state.searchPage}&page_size=10`;$('search-results').innerHTML='<div class="empty">관련 문서를 찾고 있습니다…</div>';renderSearch(await(await fetch(u,{cache:'no-store'})).json())}
async function refresh(){ $('refresh').disabled=true;try{let [h,a,p]=await Promise.all([fetch('./healthz',{cache:'no-store'}),fetchActivity(),fetchPatterns()]);renderHealth(await h.json());if(!state.prompts.length){let x=await(await fetch('./api/prompts',{cache:'no-store'})).json();state.prompts=x.prompts||[];let cats=[...new Set(state.prompts.map(p=>p.category))];$('prompt-category').innerHTML='<option value="">전체</option>'+cats.map(c=>`<option value="${safe(c)}">${safe(c)}</option>`).join('');renderPrompts()}if(!state.tools.length){let x=await(await fetch('./api/tools',{cache:'no-store'})).json();state.tools=x.tools||[];renderTools()}}catch(e){renderHealth({status:'error',error:'대시보드 데이터를 불러오지 못했습니다.',action:e.message,roots:[]})}finally{$('refresh').disabled=false}}
function activateTab(name,updateUrl=false){let target=document.querySelector(`.tab[data-tab="${name}"]`)||document.querySelector('.tab[data-tab="overview"]');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===target));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='tab-'+target.dataset.tab));if(updateUrl){let url=new URL(location.href);url.searchParams.set('tab',target.dataset.tab);history.replaceState({},'',url)}}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab,true)));
document.addEventListener('click',async e=>{let page=e.target.closest('[data-page]');if(page&&!page.disabled){let n=Number(page.dataset.page);if(page.dataset.kind==='activity'){state.activityPage=n;await fetchActivity()}if(page.dataset.kind==='pattern'){state.patternPage=n;await fetchPatterns()}if(page.dataset.kind==='search'){state.searchPage=n;await runSearch()}}let card=e.target.closest('.prompt-card');if(card&&e.target.classList.contains('prompt-toggle')){card.classList.toggle('open');e.target.textContent=card.classList.contains('open')?'접기':'전체 보기'}if(card&&e.target.classList.contains('prompt-copy')){let p=state.prompts.find(x=>x.id===card.dataset.prompt);if(p){await navigator.clipboard.writeText(p.content);$('copy-toast').classList.add('show');setTimeout(()=>$('copy-toast').classList.remove('show'),1600)}}});
let debounce;function delayed(fn){clearTimeout(debounce);debounce=setTimeout(fn,280)}$('activity-query').addEventListener('input',()=>delayed(()=>{state.activityPage=1;fetchActivity()}));$('tool-filter').addEventListener('change',()=>{state.activityPage=1;fetchActivity()});$('pattern-query').addEventListener('input',()=>delayed(()=>{state.patternPage=1;fetchPatterns()}));$('prompt-query').addEventListener('input',()=>delayed(renderPrompts));$('prompt-category').addEventListener('change',renderPrompts);$('knowledge-form').addEventListener('submit',e=>{e.preventDefault();state.searchPage=1;runSearch()});$('refresh').addEventListener('click',refresh);
const initial=new URLSearchParams(location.search);refresh().then(()=>{activateTab(initial.get('tab')||'overview');if(initial.get('q')){$('knowledge-query').value=initial.get('q');$('knowledge-root').value=initial.get('root_id')||'';state.searchPage=Number(initial.get('page')||1);runSearch()}if(initial.get('prompt_category')){$('prompt-category').value=initial.get('prompt_category');renderPrompts()}});setInterval(refresh,10000);
</script></body></html>
"""


def dashboard_html() -> str:
    return DASHBOARD_HTML
